mysite/finance/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views
#https://www.abidibo.net/blog/2014/05/26/how-implement-modal-popup-django-forms-bootstrap/
#https://www.abidibo.net/blog/2015/11/18/modal-django-forms-bootstrap-4/
app_name = 'finance'
urlpatterns = [
    path('account', views.AccountIndexView.as_view(), name='account_index'),
    path('account/detail/<int:pk>/', views.AccountDetailView.as_view(), name='account_detail'),
    #path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('account/create/', views.AccountCreateView.as_view(), name='account_create'),
    path('account/update/<int:pk>/', views.AccountUpdateView.as_view(), name='account_update'),
    path('account/delete/<int:pk>/', views.AccountDeleteView.as_view(), name='account_delete'),
    
]

"""
Without Generic Viws
from django.urls import path

from . import views
app_name = 'polls' #Used to specify what app the url belongs in template
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/detail/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    
]
"""

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('finance/', include('finance.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

"""
Without Generic Viws
from django.urls import path

from . import views
app_name = 'polls' #Used to specify what app the url belongs in template
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/detail/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    
]
"""

mysite/templates/base.html
{% load static %}
{# Load the tag library #}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}





<html>
  <head>
    <title>Financial System- mysite</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.3.0/jquery.form.min.js" integrity="sha384-qlmct0AOBiA2VPZkMY3+2WqkHtIQ9lSdAsAn5RUJD/3vA5MKDgSGcdmIv4ycVxyn" crossorigin="anonymous"></script>

  
  </head>
  <body>
    <div id="content" class="container">
      <h2>Home: <a href="{% url 'index' %}">mysite</a></h2>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Your Apps</h5>
          <p class="card-text">
            {% block content %}
            {% endblock %}</p>
        </div>
      </div>
    </div>
    {% block javascript %}

    {% endblock javascript %}
  </body>
</html>

mysite/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="m-2"><h4>finance</h4></div>
<div class="m-2"><a class="btn btn-light" href="{% url 'finance:index' %}">Account Listing</a></div>
<!--<div class="m-2"><a class="btn btn-light" href="{% url 'finance:index' %}">Category Listing</a></div>
<div class="m-2"><a class="btn btn-light" href="{% url 'finance:index' %}">Transaction Listing</a></div>-->
{% endblock %}